[lib]
crate-type = ["cdylib", "rlib"]

[package]
name = "fire_red_loop"
version = "0.1.0"
edition = "2024"

[dependencies]
fire_red_pokemon_data.workspace        = true
fire_red_map_data.workspace            = true
fire_red_text.workspace                = true
fire_red_rom_buffer.workspace          = true
fire_red_pokemon_name_buffer.workspace = true
fire_red_get_values.workspace          = true
fire_red_scanner.workspace             = true
fire_red_location_names.workspace      = true
fire_red_party_monitor.workspace       = true
fire_red_box_monitor.workspace         = true
fire_red_trainer_data.workspace        = true
fire_red_badge.workspace               = true
fire_red_memory.workspace              = true
