[lib]
crate-type = ["cdylib", "rlib"]

[package]
name = "fire_red_box_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
fire_red_get_values.workspace    = true
fire_red_memory.workspace        = true
fire_red_text.workspace          = true
fire_red_party_monitor.workspace = true
fire_red_rom_buffer.workspace    = true
fire_red_states.workspace        = true
