[package]
name = "fire_red_database"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
tracing.workspace               = true
postgres.workspace              = true
serde_json.workspace            = true
sha2.workspace                  = true
bcrypt.workspace                = true
rand.workspace                  = true
fire_red_location_names.workspace = true
fire_red_states.workspace         = true
