[lib]
crate-type = ["cdylib", "rlib"]

[package]
name = "fire_red_party_monitor"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dev-dependencies]
fire_red_pokemon_name_buffer.workspace = true

[dependencies]
tracing.workspace                        = true
arc-swap.workspace                       = true
bincode.workspace                        = true
serde.workspace                          = true
serde-big-array.workspace                = true
fire_red_get_values.workspace            = true
fire_red_text.workspace                  = true
fire_red_rom_buffer.workspace            = true
fire_red_memory.workspace                = true
