[lib]
crate-type = ["cdylib", "rlib"]

[package]
name = "fire_red_pokemon_data"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
tracing.workspace             = true
serde.workspace               = true
fire_red_rom_buffer.workspace = true
fire_red_get_values.workspace = true
