[package]
name = "fire_red_states"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
tracing.workspace                = true
bincode.workspace                = true
serde.workspace                  = true
fire_red_party_monitor.workspace = true
fire_red_pokemon_data.workspace  = true
fire_red_badge.workspace         = true
